### ISSUE TITLE
Reference to the original component

### ISSUE THREAD

**Issue by mohebifar** [mberneti/react-datepicker2#1]
Thank you for this good package. I found it very interesting that supports both Gregorian and Jalali calendars. I just think that it's nice to refer to the original package ([evandhq/react-persian-datepicker](https://github.com/evandhq/react-persian-datepicker)) in the README as it's not an actual fork and the files are copied (which is totally fine) so the users will have a hard time finding the original one.

**Comment by mberneti** [comment]
Thanks!
I'll improve the README soon.

**Comment by mberneti** [comment]
@all-contributors please add @mohebifar for doc and code
