### ISSUE TITLE
How to focus or open date picker programmatically

### ISSUE THREAD

**Issue by Shariaty** [mberneti/react-datepicker2#104]
Is it possible to focus or open date picker programmatically through a function?

**Comment by mberneti** [comment]
@Shariaty No, there isn't but can use [Calendar](https://mberneti.github.io/react-datepicker2/#example-5) as an opened date picker.

**Comment by Shariaty** [comment]
@mberneti Thank you for your reply. I was creating a range picker which have two date picker for selecting from and to values. I wanted to open the second calender as soon as the first beeing selected. I tackeled it by using pure javascript click event.

**Comment by miladreisi** [comment]
First define a ref and then use that ref to open the DatePicker
const datePickerRef = useRef(null);
datePickerRef.current.setOpen(true)

**Comment by miladreisi** [comment]
First define a ref and then use that ref to open the calendar
const datePickerRef = useRef(null);
datePickerRef.current.setOpen(true)
