### ISSUE TITLE
اختصاص inptuname

### ISSUE THREAD

**Issue by zamanphp** [mberneti/react-datepicker2#11]
میخوام از این کامپوننت در فرم جستجو استفاده کنم که از تاریخ تا فلان تاریخ
چطور میکنم به اینپوت هائی که ساخته شده نام اختصاص بدم
مثلا date_from, date_to

**Comment by hilo2120** [comment]
مشکل اتریبیوت name هنوز حل نشده؟
من میخوام datepicker رو داخل یه reduxForm استفاده کنم که با name اینپوت ها کار میکنه.
