### ISSUE TITLE
Returning Today even when the user didn't click on any date

### ISSUE THREAD

**Issue by ashkanahrabi** [mberneti/react-datepicker2#112]
There's an issue with the datepicker input.
When the user clicks inside it, the datepicker opens, but if he click off the input (without selecting any date), the _onblur_ event may fire and returns **Today**.

**Comment by mberneti** [comment]
@ashkanahrabi 
You can use the [`setTodayOnBlur`](https://github.com/mberneti/react-datepicker2/pull/103/commits/ded43855195b4e8fba0553f13e9aab41ef55672b#diff-70d836e1e5c9f4c4ee3fab8b76f74f5cR43)  property.

**Comment by ashkanahrabi** [comment]
@mberneti Thanks. I'm closing this for now but please add this to documents.
