### ISSUE TITLE
onChange is triggered even when user open and just close the picker

### ISSUE THREAD

**Issue by mashouf** [mberneti/react-datepicker2#114]
Hi,
It seems onChange is triggered even when user open and just close the picker and do not change anything.
Is there any issue with this and How can I disable this?

**Comment by mberneti** [comment]
Hi @mashouf 
You can use the [setTodayOnBlur](https://github.com/mberneti/react-datepicker2/pull/103/commits/ded43855195b4e8fba0553f13e9aab41ef55672b#diff-70d836e1e5c9f4c4ee3fab8b76f74f5cR43) property.

**Comment by mashouf** [comment]
Thanks @mberneti 
I suggest it would be better the default value be false rather than true and I did not find it in document, anyway the issue is resolved and I am closing this, thank you.

**Comment by mberneti** [comment]
Cool.
I can't do this for sake of the backward compatibility.
