### ISSUE TITLE
max property not working correctly

### ISSUE THREAD

**Issue by arashkey** [mberneti/react-datepicker2#127]
با عرض سلام
متاسفانه در زمانی که مقدار 
max
مشخص میشود، در زمانی که هیچ تاریخی انتخاب نشود، خود به خود تاریخ امروز انتخاب می شود.
حتی در زمانی که تاریخ معتبر قبل از تاریخ امروز باشد

**Comment by arashkey** [comment]
[جواب](https://github.com/mberneti/react-datepicker2/issues/114) رو پیدا کردم
اما به نظر منم باید مقدار پیش فرض فالس باشه

**Comment by mberneti** [comment]
@arashkey 
<p dir="rtl">درسته ولی بخاطر backward compatibility اینکار رو نمی‌کنیم.</p>
