### ISSUE TITLE
Locale is not a function

### ISSUE THREAD

**Issue by mahdiG** [mberneti/react-datepicker2#14]
![image](https://user-images.githubusercontent.com/4989445/43704955-7ecf08dc-9976-11e8-821c-74bb5efe71e5.png)
My code worked fine but recently I get this error. I haven't changed anything.

**Comment by mberneti** [comment]
@mahdiG can i see your code?

**Comment by mahdiG** [comment]
Apparently the back-end has changed the json so the inputValue has changed and causes this error.
