### ISSUE TITLE
timepicker not working

### ISSUE THREAD

**Issue by alimzadeh** [mberneti/react-datepicker2#18]
با سلام و تشکر از زحمت شما؛
در زمان استفاده از این کامپوننت با دو تا مشکل مواجه شدم:
۱. در مرتبه اول که بخش انتخاب تاریخ نمایش داده میشه، باکس مربوط به انتخاب زمان نمایش داده نمیشه (در شرایطی که مقدار پیش فرض نداشته باشه)
۲. بعد از انتخاب تاریخ که باکس انتخاب زمان نمایش داده میشه، غیر فعال هست و امکان انتخاب زمان وجود نداره.

**Comment by mberneti** [comment]
<p dir="rtl"> سلام @alimzadeh 
<br>حتما در اولین فرصت بررسی می‌کنم اما مشکل مورد دوم رو توی دمو نمی‌بینم.
</p>

**Comment by alimzadeh** [comment]
ممنون؛
مشکل غیر فعال بودن
timepicker
(مشکل دوم) 
با تغییر 
z-index
برطرف شد. ولی همچنان مشکل اول برای من وجود داره.

**Comment by mberneti** [comment]
<p dir='rtl'>
@alimzadeh من این issue رو می‌بندم چون بدون داشتن نمونه کد یا مستندات کافی که مشکل دیده بشه کاری نمیشه کرد.
</p>

**Comment by alimzadeh** [comment]
اگر در همون مثال اول (Default)
متد سازنده به این شکل تغییر کنه:
  constructor(props) {
    super(props);
    this.state = {value: null}; // default value removed
  }
میتونید مشکل رو مشاهده کنید. اگر زمان، مقدار پیش فرض نداشته باشه مرتبه اول نمایش داده نمیشه.

**Comment by mberneti** [comment]
@alimzadeh
 حتما بررسی می‌کنم

**Comment by mberneti** [comment]
<p dir="rtl">@alimzadeh از ثبت این گزارش بسیار سپاسگزارم
<br />
هر دو موردی که گفته بودید در نسخه جدید برطرف شد.
</p>

**Comment by mberneti** [comment]
fixed this in https://github.com/mberneti/react-datepicker2/commit/b0a300e659f2589f1996498b42a7dc7e3e358f5e
