### ISSUE TITLE
bootstrap modal bug

### ISSUE THREAD

**Issue by AmirGh72** [mberneti/react-datepicker2#2]
datepicker appearing behind of bootstrap modal. what should I do?

**Comment by mberneti** [comment]
can u show me a example with [jsfiddle](https://jsfiddle.net/)?

**Comment by AmirGh72** [comment]
**my problem image:**
![test](https://user-images.githubusercontent.com/25684809/29749554-392bc004-8b44-11e7-8059-b5003e5de370.png)

**my react code:**
`
import React from 'react';
import moment from 'moment-jalaali';
import DatePicker from 'react-datepicker2';

class TestDatePicker extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      date : moment()
    };
  }

  render() {
    return (
        <div>
          <h3>testDatePicker</h3>

          <button className="btn btn-sm btn-primary btn-block" id="formButton" data-title="test" data-toggle="modal" data-target="#test">
            <span className="glyphicon glyphicon-plus"></span> test
          </button>


          <div className="modal fade" id="test" tabIndex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div className="modal-dialog">
              <div className="modal-content">
                <div className="modal-header">
                  <button type="button" className="close" data-dismiss="modal" aria-hidden="true"><span className="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                  <h4 className="modal-title custom_align" id="Heading">New Stay Request</h4>
                </div>
                <div className="modal-body">
                  <div className="form-group">   
                    <DatePicker className="form-control" value={this.state.date} isGregorian={false} onChange={date => this.setState({ date })} />
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    );
  }
}

export default TestDatePicker;
`

**Comment by AmirGh72** [comment]
**my problem image:**
![test](https://user-images.githubusercontent.com/25684809/29749570-df7afaec-8b44-11e7-9883-87085d121d96.png)

**my react code:**
`
import React from 'react';
import moment from 'moment-jalaali';
import DatePicker from 'react-datepicker2';


class TestDatePicker extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      date : moment()
    };
  }


  render() {
    return (
        <div>
          <h3>testDatePicker</h3>

          <button className="btn btn-sm btn-primary btn-block" id="formButton" data-title="test" data-toggle="modal" data-target="#test">
            <span className="glyphicon glyphicon-plus"></span> test
          </button>


          <div className="modal fade" id="test" tabIndex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div className="modal-dialog">
              <div className="modal-content">
                <div className="modal-header">
                  <button type="button" className="close" data-dismiss="modal" aria-hidden="true"><span className="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                  <h4 className="modal-title custom_align" id="Heading">New Stay Request</h4>
                </div>
                <div className="modal-body">
                  <div className="form-group">   
                    <DatePicker className="form-control" value={this.state.date} isGregorian={false} onChange={date => this.setState({ date })} />
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    );
  }
}
`

**Comment by AmirGh72** [comment]
**my problem image:**  
![test](https://user-images.githubusercontent.com/25684809/29749603-5249d1ba-8b45-11e7-8dc8-f0ca9a4e0af2.png)

```
import React from 'react';
import moment from 'moment-jalaali';
import DatePicker from 'react-datepicker2';

class TestDatePicker extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      date : moment()
    };
  }

  render() {
    return (
        <div>
          <h3>testDatePicker</h3>

          <button className="btn btn-sm btn-primary btn-block" id="formButton" data-title="test" data-toggle="modal" data-target="#test">
            <span className="glyphicon glyphicon-plus"></span> test
          </button>


          <div className="modal fade" id="test" tabIndex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div className="modal-dialog">
              <div className="modal-content">
                <div className="modal-header">
                  <button type="button" className="close" data-dismiss="modal" aria-hidden="true"><span className="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                  <h4 className="modal-title custom_align" id="Heading">New Stay Request</h4>
                </div>
                <div className="modal-body">
                  <div className="form-group">   
                    <DatePicker className="form-control" value={this.state.date} isGregorian={false} onChange={date => this.setState({ date })} />
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    );
  }
}
```
