### ISSUE TITLE
Maximum update depth exceeded error on date select

### ISSUE THREAD

**Issue by pouyajabbarisani** [mberneti/react-datepicker2#20]
Below error occurs when selecting the date:

_Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops._

my usage: 
```
     <DatePicker
            onChange={(value) => props.actions.setCustomDate(value)}
            value={typeof props.myReducer.date != 'undefined' ? moment(props.myReducer.date) : null }
      />

```
(I'm using stateless component)

<img width="1249" alt="Screen Shot 1398-03-11 at 16 38 17" src="https://user-images.githubusercontent.com/13765850/58748304-c2800080-848b-11e9-90e8-0f6f8f5cab84.png">

**Comment by mberneti** [comment]
I need to see more codes @pouyajabbarisani

**Comment by pouyajabbarisani** [comment]
What section of code do you need? 
I've tried the onChange section without using redux's action and/or other types of functions and it works as expected. (using console.log eg: onChange={(value) => console.log(value)})

**Comment by pouyajabbarisani** [comment]
Just now, I also tried with **classical component** and it occurs the **same error**.

**Comment by mberneti** [comment]
can i see this **classical component** ?

**Comment by pouyajabbarisani** [comment]
Sure,
<img width="1079" alt="Screen Shot 1398-03-11 at 16 44 13" src="https://user-images.githubusercontent.com/13765850/58748353-bba5bd80-848c-11e9-8ab5-7e4d81f745a1.png">

**Comment by pouyajabbarisani** [comment]
Yeah, sure:

<img width="1082" alt="Screen Shot 1398-03-11 at 16 45 43" src="https://user-images.githubusercontent.com/13765850/58748361-db3ce600-848c-11e9-8bf6-0d09bf36fa87.png">

**Comment by mberneti** [comment]
I'll test it ASAP

**Comment by mberneti** [comment]
Injected value in onChange call back and value property of datepicker component should be exactly the same[
![727522C4-2807-4FFF-8CBC-15F716808F01](https://user-images.githubusercontent.com/3443365/58750866-7a250a80-84ac-11e9-9297-3dc31d755cd7.jpeg)
](url)

**Comment by pouyajabbarisani** [comment]
So, how I can set the default value? because It's value isn't a simple JS date

**Comment by mberneti** [comment]
There is multiple ways:
1.Add a value state to the single agency and in datepicker onChange callback after setting new value call setAdminSingleAgency
2.Add new prop to the agencyReducer for storing simple JS date and then in setAdminSingleAgency after setting this new property (like basicExpireDate), set your system basicExpireDate
And etc

**Comment by pouyajabbarisani** [comment]
I realized that it needs the 'moment' format type and I have split my date as down below:

```
var basicDate = new Date(result.data.agency.basicExpire)
var basicTrueFormat = moment(basicDate.getFullYear() + ' ' + (basicDate.getMonth() + 1) + ' ' + basicDate.getDay(), 'YYYY M D')
// then I gave basicTrueFormat instead of **props.adminSingleAgencyReducer.initialData.basicExpire**
```

Done, thanks.
