### ISSUE TITLE
how to disable part of date

### ISSUE THREAD

**Issue by fatemehqasemkhani** [mberneti/react-datepicker2#23]
I'd like to add min date and max date, just enable part of month.
Is it possible?

**Comment by mberneti** [comment]
yep, I'm working on it. @fatemehqasemkhani

**Comment by mberneti** [comment]
@fatemehqasemkhani now u can use docs for 
[limit selection days](https://mberneti.github.io/react-datepicker2/#example-5) or [disable some ranges of date](https://mberneti.github.io/react-datepicker2/#example-6)

**Comment by fatemehqasemkhani** [comment]
Thank's.

**Comment by mberneti** [comment]
you're welcome

**Comment by anniestudent** [comment]
Is it possible to disable a particular weekday e.g. Friday?
