### ISSUE TITLE
css of calendar

### ISSUE THREAD

**Issue by hadiMh** [mberneti/react-datepicker2#26]
Hi, this libaray is great. Thank you
I have problem to disable the box-shadow of the calendar. I gave it the style of `styles={{boxShadow: 'none' }}` but it overrides all of the styles and just use this style. I tried to find a file in your project for all of the styles of the calendar to pass it along side of my custom box-shadow but i couldn't find your styles.
Please tell me how can I disable the box-shadow of the calendar. And in general how can I customize any style of the calendar?
Tnx in advance

**Comment by mberneti** [comment]
Hey, thanks!
This [link](https://github.com/mberneti/react-datepicker2/blob/cf25e20134d0f1f10b322e9cdf08438bb7e85362/src/styles/style.scss#L8) refer to the project main style file.
I'll improve calendar style customization ASAP but for now u can override calendarContainer class like this:
```
.calendarContainer {
    -moz-box-shadow: none;
    -webkit-box-shadow: none;
    box-shadow: none;
}
```
