### ISSUE TITLE
Calendar selected date does not update when value is changed outside of calendar component

### ISSUE THREAD

**Issue by alexwileyy** [mberneti/react-datepicker2#28]
It appears that the calendar does not update when the calendar value is changed outside of the calendar component itself.

For example, I have a calendar component like so
```
<Calendar isGregorian={true}
    value={selectedDate}
    onChange={value => dateChange(value)}
/>
```

When the `selectedDate` is passed in on component mount it sets the date correctly showing the current date in a blue outline and the selected date to the date that was passed in via moment.

However, when I try to change the value like so (example uses hooks):
```
setSelectedDate(new moment().add(10, 'days'));
```
The calendar does not update the currently selected date that is displayed on the calendar.

I know that the selected date value is changing as i'm showing the date on the UI and I can see that the date changes when I change it with the hook.

Could this get fixed?

**Comment by mberneti** [comment]
I'll check it ASAP

**Comment by mberneti** [comment]
@alexwileyy I tested it, and there isn't any problem with react hook.
u can see the usage sample of the ReactHook with this datepicker [here](https://mberneti.github.io/react-datepicker2/#example-9)
