### ISSUE TITLE
Incorrect format shown when ` isGregorian` field changed multiple

### ISSUE THREAD

**Issue by alimzadeh** [mberneti/react-datepicker2#29]
Hi,
when I change `isGregorian` state in demo (header section) multi times, the format goes incorrect.
this behavior occurred also in my app.
tnx

**Comment by mberneti** [comment]
Hi
I saw this bug too, to be honest, But this bug had no priority for me.
I'll fix it ASAP.

**Comment by alimzadeh** [comment]
Sorry for my low accuracy,
First time switch, still has bug :|

**Comment by mberneti** [comment]
@alimzadeh Thank you for the contribution, I accepted and merged your PR yesterday and released new version of this package on npm (v3.0.2).
You can see new updates on the [demo page](https://mberneti.github.io/react-datepicker2/), Is it still there?

**Comment by alimzadeh** [comment]
Unfortunately `first time` switch bug still there :( and the code I write in last comment, is my temporary fix for this bug. Because that solution is not good enough to publish in repository, I didn't push this to repository.

**Comment by mberneti** [comment]
Unfortunately I can't see first time switching bug on the demo page.
And this is your PR https://github.com/mberneti/react-datepicker2/pull/30 , Isn't it?

**Comment by alimzadeh** [comment]
Yes, this is my PR and I saw your new release, but there is still a bug:
my test scenario:

step 1)
![10](https://user-images.githubusercontent.com/11006666/62419630-59d71f00-b69a-11e9-9960-12cd9e48cf3f.png)
**Correct** (initial state)

Step 2)
![20](https://user-images.githubusercontent.com/11006666/62419631-63608700-b69a-11e9-8fe5-f6b52b806a76.png)
**Wrong**! (the first time switch is clicked, format is Ok, **value** is wrong)

Step 3)
![30](https://user-images.githubusercontent.com/11006666/62419633-6ce9ef00-b69a-11e9-9f26-5b77b41bc573.png)
**Correct**

Step 4)
![40](https://user-images.githubusercontent.com/11006666/62419635-72dfd000-b69a-11e9-9ee8-5dcf548187b6.png)
**Correct**

Tnx for your attention

**Comment by mberneti** [comment]
Great, I'll check the code ASAP.
