### ISSUE TITLE
خطا در زمان انتخاب ماه

### ISSUE THREAD

**Issue by pMonfared** [mberneti/react-datepicker2#4]
<div dir="rtl">

1. نمایش تاریخ به صورت فینگلیش هست
2. در زمان انتخاب ماه کامپوننت از کار می افته

![image](https://user-images.githubusercontent.com/10448255/30997519-3fab576e-a4d5-11e7-9571-bf32ed565d92.png)

![image](https://user-images.githubusercontent.com/10448255/30997512-32f4bb00-a4d5-11e7-9f0e-e1e1a39c0a41.png)

@mberneti 
</div>

**Comment by pMonfared** [comment]
```
import React from 'react'
import moment from 'moment-jalaali'
import DatePicker from 'react-datepicker2'
import createReactClass from 'create-react-class'

let CsDatePicker = createReactClass({
    getInitialState() {
        return {
            value: moment()
        }
    },
    render() {
        return <DatePicker
            isGregorian={false}
            onChange={value => this.setState({ value })}
            value={this.state.value}
        />
    }
})

export default CsDatePicker
```

**Comment by aminsource** [comment]
loadPersian method:

moment.loadPersian()
