### ISSUE TITLE
add year picker

### ISSUE THREAD

**Issue by whossein** [mberneti/react-datepicker2#43]
add year picker when click on year, thanks

**Comment by hilo2120** [comment]
Year picker is essential for inputs like birthdate,
It would be great if you could add this feature in the next version,

**Comment by mberneti** [comment]
@hilo2120 I think so, I'll work on it next week.

**Comment by mberneti** [comment]
@hilo2120 @whossein this feature added in v3.1.0 and published on the NPM.

**Comment by nrmz** [comment]
how to use this feature?
