### ISSUE TITLE
defaultValue property not working

### ISSUE THREAD

**Issue by aliazizi** [mberneti/react-datepicker2#45]
I use this component with defaultValue ( not value )

here is my code

```<DatePicker
                defaultValue={moment('1396/7/6', 'jYYYY/jM/jD')}
                isGregorian={false}
                inputFormat={'jYYYY'}
                inputJalaaliFormat={'jDD'}
              />
```

And I get this error

`TypeError: this.state is undefined` and here  the line`

```
key: "getValue",
    value: function getValue(inputValue, isGregorian, timePicker) {
      if (!inputValue) return '';
      var inputFormat = this.state.inputFormat; // -> this line

```

**Comment by mberneti** [comment]
@aliazizi 
Why you don't use the value?
I think I should remove this prop, cuz we don't need this.

**Comment by aliazizi** [comment]
@mberneti because of this
https://reactjs.org/docs/uncontrolled-components.html

it's part of react feature.

**Comment by aliazizi** [comment]
@mberneti please check my comment
