### ISSUE TITLE
How to kill the 'Today' button?

### ISSUE THREAD

**Issue by Aid19801** [mberneti/react-datepicker2#52]
Hi guys, thanks very much for your work on this.

I'm trying to kill the Today button.

Been having a good comb through the code but i can't find `<button class="selectDay">` anywhere.

Tried:
- looking at Calendar.js, dev tools suggests the button is at `CalendarContainer` level

```
   <div className={styles.calendarContainer + ' ' + jalaaliClassName + className}>
        {mode === 'monthSelector' ? this.renderMonthSelector() : this.renderDays()}
      </div>
```
But that ^^ just renders month/day selectors.

- looking at `onClickOutside` module. Wondered if it might listen for a click on a button and then assign a value of Date.now() or something. But seems onClickOutside is literally just there to open/close the calendar component.

- searching for the `selectDay` styles / className. No joy.

Any advice on where to find it?

Might just kill the element with a style rule otherwise.

**Comment by Aid19801** [comment]
UPDATE: I have gotten around this by injecting a disgustingly-hacky `display: none` at the top of my app for `selectToday`

Would love to see/assist in adding an options prop that kills that button though, if poss. 

Thanks. x

**Comment by mberneti** [comment]
Hi @Aid19801 
Thanks for reporting the issue.
I'll add this feature ASAP.

**Comment by mberneti** [comment]
@Aid19801 
Added new showTodayButton property to the Datepicker and you can see the usage of this feature [here](https://mberneti.github.io/react-datepicker2/#example-2) on the demo page. 
![image](https://user-images.githubusercontent.com/3443365/71308148-ea29bc80-240d-11ea-8c16-63b973031d75.png)
