### ISSUE TITLE
Empty input bug in jalaali date

### ISSUE THREAD

**Issue by eternity-wing** [mberneti/react-datepicker2#54]
in jalali date time picker with persian digits if you clear the input value it raise exception. you can check it by clearing the second example's input.

**Comment by mberneti** [comment]
@eternity-wing Thank you, It's a critical issue.

**Comment by eternity-wing** [comment]
You're welcome, is it solveable!?

**Comment by mberneti** [comment]
@eternity-wing in a few minutes :D 👨‍💻
