### ISSUE TITLE
Warning: Failed prop type: Invalid prop `inputReadOnly` of type `boolean` supplied to `DatePicker`, expected `object`.

### ISSUE THREAD

**Issue by aliazizi** [mberneti/react-datepicker2#57]
```Warning: Failed prop type: Invalid prop `inputReadOnly` of type `boolean` supplied to `DatePicker`, expected `object`.```

the prop type of InputReadOnly is wrong

**Comment by mberneti** [comment]
@aliazizi 
Thanks for your useful reports and contribution, I'll fix it ASAP.
