### ISSUE TITLE
Module not found: Can't resolve 'indexof' in react-datepicker2\dist

### ISSUE THREAD

**Issue by irnazari200** [mberneti/react-datepicker2#58]
hi guys there is a problem with installing this component .i get this error after installing:

/node_modules/react-datepicker2/dist/index.js
Module not found: Can't resolve 'indexof' in 'D:\pezeshkyaran\code\react project\test for calerdar\my-app\node_modules\react-datepicker2\dist'

it appears in package.jason  but still not working:
"react-datepicker2": "^3.0.6",

whats wrong??

**Comment by mehrdad517** [comment]
این مشکل هنوز حل نشده؟

**Comment by mberneti** [comment]
@mehrdad517 
حل شده

**Comment by mehrdad517** [comment]
این مشکل هنوز هست 
نسخه 3.0.14
طبق داکیومنت خودش 
تست کردید؟

**Comment by mehrdad517** [comment]
نسخه روی 
npm
مشکل داره
پکیج رو از روی گیت هاب دانلود کردم و اکسترکت کردم توی 
node_module
حل شد
@mberneti

**Comment by mberneti** [comment]
@mehrdad517 
<div dir="rtl">
من این مشکل رو با ورژن 3.0.14 npm ندارم.
<br/>
حدس می‌زنم پکیج شما بخوبی بروزرسانی نمیشد.
</div>

**Comment by irnazari200** [comment]
عرض سلام و درود
پوزش بنده بابت پاسخگویی دیر به ایمیلتان را بپذیرید .متاسفانه مشکلی پیش امده
بود.
امروز نصبش کردم خدارو شکر درست شده و نصب میشه .منتها یه مشکلی که برام پیش
اومده اینه که من این کامپوننت رو روی framework7  استفاده می کنم و باعث شده
که درست نشون داده نشه.ظاهرا استایل ها به تداخل میخورند و هر چه تلاش کردم
نتوانستم تقویم را ظاهر کنم ممنون میشم بفرمایید چکار کنم .عکس نحوه نمایشش رو
هم براتون فرستادم.
با تشکر
[image: 2020-01-03 08_20_29-dr.png]

**Comment by mberneti** [comment]
@irnazari200 
<div dir="rtl">
سلام
<br />
خواهش می‌کنم، برای بررسی نیاز به نمونه کد شماست و اینکه تصویر مشکل شما به خوبی بارگذاری نشد.
</div>

**Comment by irnazari200** [comment]
عرض سلام مجدد
جناب برنتی خدارو شکر درست شد. نیاز بود یه z-index=10000  بهش میدادم!فکر نمی
کردم فریم ورک 7 تا این حد به استایل های خودش z-index داده باشه.
بازم تشکر میکنم از پاسخگویی و کمکتون بابت نصب این تقویم خوب، ممنون

**Comment by mberneti** [comment]
@irnazari200 
<div dir="rtl">
سلام
<br />
خدارو شکر مشکلتون حل شد.
<br />
واقعا
 مشکل عجیبی بود.
</div>

**Comment by irnazari200** [comment]
فقط اگر یه اپشنی به تقویم اضافه می کردین که راحت بشه چند سال کم و زیاد کرد
خیلی خوب میشد. الان یه قسمت هست که میخام تاریخ تولد کاربر رو بگیرم و طرف
مجبوره یه سال یه سال کم کنه تا مثلا برسه به 1365 ! یکم سخته خدایی. امکانش
هست این اپشن رو اضافه کنید مثلا یه اسکرول بخوره که سریع سال انتخاب بشه؟

**Comment by irnazari200** [comment]
مهندس باید ببخشید من اینقدر مزاحمتون میشم. یه مشکل دیگه ام اینه که وقتی توی
گوشی کاربر تقویم رو باز میکنه صفحه کلید هم باهاش باز میشه که اصلا جالب نیست
متد preventDefault()  v رو روش تست کردم ولی جواب نداد ،توی گوگل هم سرچ کردم
ولی به نتیجه نرسیدم. شما نظری ندارد که چطور جلوی باز شدن کیبورد رو بگیرم؟

‪On Sat, Jan 4, 2020 at 11:16 PM ‫محسن نظری‬‎ <irnazari200@gmail.com>
wrote:‬

> فقط اگر یه اپشنی به تقویم اضافه می کردین که راحت بشه چند سال کم و زیاد کرد
> خیلی خوب میشد. الان یه قسمت هست که میخام تاریخ تولد کاربر رو بگیرم و طرف
> مجبوره یه سال یه سال کم کنه تا مثلا برسه به 1365 ! یکم سخته خدایی. امکانش
> هست این اپشن رو اضافه کنید مثلا یه اسکرول بخوره که سریع سال انتخاب بشه؟
>
> On Sat, Jan 4, 2020 at 2:26 PM mohammadreza berneti <
