### ISSUE TITLE
Unexpected identifier in import moment-jalaali

### ISSUE THREAD

**Issue by mehdiraized** [mberneti/react-datepicker2#60]
i see this bug in ssr mode
```
/Project/node_modules/react-datepicker2/dist/index.js:1
import moment$2 from 'moment-jalaali';
       ^^^^^^^^

SyntaxError: Unexpected identifier
```

**Comment by mberneti** [comment]
@mehdiraized 
I think It's something about the last changesets in the building method.
I'll check it soon.

**Comment by mberneti** [comment]
@mehdiraized Can you test the latest changesets (v3.0.11)?
It seems OK after this commit https://github.com/mberneti/react-datepicker2/commit/5a68ee9a80ba1f214b362156299342bb21c7aef8
![newupdate](https://user-images.githubusercontent.com/3443365/71307913-8ea9ff80-240a-11ea-85c8-360b10e83589.PNG)
