### ISSUE TITLE
I Got Error When Try to test

### ISSUE THREAD

**Issue by shayegh** [mberneti/react-datepicker2#64]
Hi,
I'm using your component and when I try to Test my app I get this Error:
```
 Test suite failed to run

    \node_modules\react-datepicker2\dist\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import momentJalaali from 'moment-jalaali';
                                                                                                    ^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier
```
My Test Code
```JSX
test('This is test', () => {
    console.log('Hello World !');
});

it('renders without crashing', () => {
    shallow(<App />);
});
```

**Comment by mberneti** [comment]
@shayegh 
I haven't any problem with this component testing.
I think it's something about your JS project configs.

**Comment by alirni** [comment]
Hi!
I have exactly the same problem.
This error only occurs for components that use this module.

Didn't you have a similar problem?

**Comment by mberneti** [comment]
@mberneti I'll check it soon.

**Comment by alirni** [comment]
You don't need check it.
I update the module and the problem was fixed.
@mberneti tnx 🙏

**Comment by mberneti** [comment]
@alirni Cool 👍
