### ISSUE TITLE
showToggleButton

### ISSUE THREAD

**Issue by sassankarimi** [mberneti/react-datepicker2#65]
hello.
When use props "showToggleButton" and click on this button in calender format of input value not change.for example when click on toggle butten inside calender, date correctly changed to jalali but input value not change to jalali.
 when I declare button in my component and use that button,input format correctly changed by isGregorian.
but I want change date format by showToggleButton props.
thanks.

**Comment by mberneti** [comment]
Hello @sassankarimi 
I'll check it ASAP.

**Comment by sassankarimi** [comment]
hello.
I want to ask,this problem fixed or not?

**Comment by mberneti** [comment]
Hi @sassankarimi 
Yes, this bug fixed today.
Now you can see this feature on the [demo page](https://mberneti.github.io/react-datepicker2/#example-13)
<br />
![newfeature](https://user-images.githubusercontent.com/3443365/73653341-3bc89680-469e-11ea-8ebd-a9421b87d72e.png)
