### ISSUE TITLE
Error  import momentJalaali from 'moment-jalaali'

### ISSUE THREAD

**Issue by afsanefda** [mberneti/react-datepicker2#67]
after two months I rebuild my project but it keeps getting this error:

  ```
  "react-datepicker2": "^3.0.3",
  "react": "^16.9.0",

  node v10.16.3   or even  node v8.10.0
```
```
/node_modules/react-datepicker2/dist/index.js:1
import momentJalaali from 'moment-jalaali';
```

Is something changed in the library? It was working fine before! and my production application works fine with the date picker but locally it is not!

**Comment by mberneti** [comment]
@afsanefda This package has a lot of major updates and I think you should reinstall it.

**Comment by afsanefda** [comment]
The main problem was the node version and I think some of my babel configs were broken! 
remove node_modules folder and yarn install or yarn upgrade.
remove the build folder also and rebuild the project!  In my case, it worked fine!

**Comment by mmjd** [comment]
change format in rollup.config.js to 'cjs' and run build:dist again to build for commonjs.
