### ISSUE TITLE
returning date value

### ISSUE THREAD

**Issue by mortezagolzan** [mberneti/react-datepicker2#68]
hi
how can I get back the value of date?!
according to your doc the value just return a moment like :

F {_isAMomentObject: true, _isUTC: false, _pf: {…}, _locale: Locale, _d: Wed Jan 15 2020 00:00:00 GMT+0330 (Iran Standard Time), …}
_isAMomentObject: true
_isUTC: false
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", _ordinal: "%dم", _dayOfMonthOrdinalParse: /\d{1,2}/, …}
_d: Wed Jan 15 2020 00:00:00 GMT+0330 (Iran Standard Time) {}
_isValid: true
_jDiff: 0
__proto__: Moment

I just tried value._d to get the date but it didn't work.
how could I do this?!

**Comment by aliazizi** [comment]
You can get date from moment
https://stackoverflow.com/a/26744045/1827594
