### ISSUE TITLE
Get unresolved dependecy error

### ISSUE THREAD

**Issue by mohammadranjbar** [mberneti/react-datepicker2#70]
I got  unresolved dependecy error for react-datepicker2 in IDE and when building with rollup, 
and I found that you said this in your package.json
```
"main": "dist/index.js",
  "browser": "dist/react-datepicker2.min.js",
  "module": "dist/es/index.js",
```
but your dist folder has just `index.js` file,
I would appreciate if you fix it

**Comment by mberneti** [comment]
@mohammadranjbar Thank you for issue reporting, I fix it.
