### ISSUE TITLE
Wrong styles when isGeorgian is false

### ISSUE THREAD

**Issue by theMasix** [mberneti/react-datepicker2#87]
Hello.
When the isGerogian is true, the DatePicker element classes are:
```
tether-element tether-element-attached-center tether-target-attached-center tether-enabled tether-element-attached-bottom tether-target-attached-top
```
but when it's false:
```
tether-element undefined
```

So the styling such as positioning and z-index will be wrong when it works with Jalali Date.

I'm new to this project but because it's an strange issue, I think it causes since your last commit. It's a new issue actually.

**Comment by mberneti** [comment]
@theMasix Thank you.
You noticed an important point and I'll check it.

**Comment by theMasix** [comment]
Sorry dude. I think my issue report was a mistake and the problem is somewhere else with the styles not the classes! I'm so sorry if I waste your time to figure out what the bug is.
Actually I figured out that It's a problem with your CSS not the classes that you assign to elements.

Now the problem with z-index and positioning is general and doesn't matter if the DatePicker is set to Georgian or not... It was my mistake bro.

And the conclusion is your general positioning and z-index is not good and should be fix I think.
I could send the problem as video to you. Telegram or wherever you say.

**Comment by mberneti** [comment]
@theMasix Great!
You can find me by @mberneti
