### ISSUE TITLE
عدم نمایش ماه و تاریخ شمسی

### ISSUE THREAD

**Issue by hanieas** [mberneti/react-datepicker2#88]
من دقیقا همون فرمی که فرمودید نصب و استفاده کردم ولی تاریخ و ماه ها به صورت میلادی نمایش داده میشن چطوری میتونم حلش کنم؟

**Comment by mberneti** [comment]
@hanieas 
<p dir="rtl">
اگر صفحه‌ی دمو را دیده باشید مثالش هست که برای حالت شمسی مقدار پراپرتی isGregorian برابر false
باید باشد.
</p>
https://mberneti.github.io/react-datepicker2/#example-1
