### ISSUE TITLE
Calendar position

### ISSUE THREAD

**Issue by buglessir** [mberneti/react-datepicker2#94]
I've used it inside a Reactstrap Collapse box, but calendar position has problem (sticks to the top of the page) and I think it's because the parent element is collapsible and has relative position ?! ...

Collapse Component: https://reactstrap.github.io/components/collapse/

Thanks

**Comment by buglessir** [comment]
@mberneti

**Comment by aliazizi** [comment]
Can you reproduce it in https://codepen.io/?

**Comment by buglessir** [comment]
> Can you reproduce it in https://codepen.io/?

Not important!
I've used another package
